# DataSource Config
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:F:\database;MODE=MySQL;NON_KEYWORDS=USER
    username: root
    password: test

  h2:
    console:
      enabled: true
server:
  port: 8083

# 配置MyBatis日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

